### ISSUE TITLE
improving job submission and management in queues

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#2684]
Decided that I'll put together a list of things we want to improve so we can group discus and address. 

- [ ] Currently, when a job completes it will issue a complete_job call, that will issue N validators to validate output; best scenario we issue 2 new jobs. The best will be to be able to manage the local environments and only issue jobs that make sense; AKA issue a new job for N-1 validators, [original report](https://github.com/biocore/qiita/issues/2682).
- [ ] Qiita should be aware of which queues/jobs the completed job was ran on. This information is currently loaded in the QIITA_CONFIG_FILE, which means that if a job is ran in queue A and the servers are running on queue B, the finishing jobs will be issue in A vs B.
- [ ] Allow delete of jobs. I _believe_ that if we simply error the job in Qiita, the next time it tries to update the heartbeat the job in the queue will die cause you can update the heartbeat of an error job but need to test. [Original issue](https://github.com/biocore/qiita/issues/2307).
- [ ] [This](https://github.com/biocore/qiita/issues/2042) came up during the deblur reprocessing; the server goes down (which automatically restarts) and the job can't be started so it stays queued but the job is not retried. BTW the error we get when trying is: `qstat: cannot connect to server`
- [ ] Re-evaluate the need of internal validations ... a good example of why we need is deblur and shotgun, as it can produce an empty BIOM silently and the validation catches it.
- [ ] Use the plugin_launcher and the private_launcher during job submission, currently not used 
- [ ] Somehow be able to determine if the job in the queue has died ...

**Comment by antgonza** [comment]
Closing as this has been superseded by https://github.com/biocore/qiita/issues/2782
