### ISSUE TITLE
EBI Submission

### ISSUE THREAD

**Issue by adamrp** [biocore/qiita#314]
List of things that need to be done:

~~Creation of the `Ontology` object in qiita_db @adamrp (#317)~~
~~Ontology lookups @adamrp~~
- [x] #100 (change location of `ebi_study_accession` and `ebi_submission_accession` columns) @antoniog
- [x] MD5 calculations/checking Justine, @wasade
- [x] Logging @squirrelo
- [x] Test code @teravest, @ElDeveloper @wasade @adamrp
- [x] qiime to travis @antoniog

Click commands:
- [x] Condense command interface (#331, @adamrp)
- [x] Generate XML files (#333, @adamrp)
- [x] Submit XML files (call to Aspera SCP) (#333, @adamrp)

Interface
~~Data upload workflow #315 - @teravest, @wasade and @ElDeveloper~~
